### ISSUE TITLE
NameError: name 'colorama' is not defined

### ISSUE THREAD

**Issue by chaiheng753** [tartley/colorama#181]
I am running a simulator which uses colorama on 

(a) Ubuntu on Windows 10
Python 3.6.5 with colorama 0.3.9 (Build: py36h489cec4_0)

(b) Windows 10 via Anaconda Prompt.
Python 3.6.6 with colorama 0.3.9 (Build: py36h029ae33_0)

The simulator runs well on Ubuntu-on-Windows-10. I intend to test the simulation on Windows 10, presuming that it could run faster than on Ubuntu-on-Windows-10.

However, when running the simulator on Windows 10, I got this error message:
**_NameError: name 'colorama' is not defined_**
(No error message when running on  Ubuntu-on-Windows-10).

Can anyone advise me how can I solve this problem? Do you think the different "builds" are the cause? Thank you.

Heng

**Comment by eternaleclipse** [comment]
There are two probable explanations:

1.  Your script does not attempt to import ```colorama``` on Windows.
2.  Your script attempts to import ```colorama``` which is missing on your Windows system, this raises an ```ImportError``` but the code is in a ```try / except``` block which ignores the exception, it probably fails shortly after in ```colorama.init()```.

Either way, this doesn't look like a bug in ```colorama``` (since ```colorama``` is not loaded in your namespace).
I suggest closing this issue.
