### ISSUE TITLE
Why can't background color be bright?

### ISSUE THREAD

**Issue by Ahmed-Mokhles** [tartley/colorama#204]
Hello!
I noticed that the background color can't be set to be bright (or at least I don't know how to do it)
So can you please fix this? And if it is possible, can you tell me how?
Thanks

**Comment by wiggin15** [comment]
Hi @Ahmed-Mokhles . As far as I know there is no "standard" way to add make the background color bright, but you can use the "ex" color codes to set bright background colors, like so:

```python
print(colorama.Back.LIGHTRED_EX + 'a' + colorama.Back.RESET)
```

The reason these color codes are marked with "EX" is because they are not part of the ANSI standard, but they should work on most modern terminals, and colorama will convert them correctly on Windows. Hope this helps!
