### ISSUE TITLE
Call to deinit() doesn't work with one init() call

### ISSUE THREAD

**Issue by naltun** [tartley/colorama#213]
Here's a screenshot:

![image](https://user-images.githubusercontent.com/7507990/53039434-39e5d300-344d-11e9-9e2f-99e5a5bb4f20.png)

Here's what my import statement looks like:
`from colorama import init, Fore`

**Comment by wiggin15** [comment]
Hi @naltun . It seems like you didn't import the function `deinit` so the interpreter doesn't recognize it.
Fix your import statement like this: `from colorama import init, deinit, Fore`

**Comment by naltun** [comment]
@wiggin15 Thanks!

I see that in both `demo01.py` and `demo02.py` there are no calls to `deinit()`. If we don't deinitialize ANSI colors, won't the terminal retain ANSI colors? Shouldn't we always call `deinit()`?

**Comment by wiggin15** [comment]
@naltun `colorama.init` wraps the process stdout and stderr streams with colorama streams that can read and convert ANSI codes. `deinit` resets the stdout and stderr streams to the originals. Since these streams are specific to a process, when you exit the process they are gone, whether they are wrapped or not. This means that you don't have to call `deinit` before you exit the process.

On the other hand, terminals do remember the color state given by ANSI codes (or by API in the case of Windows), and if you don't reset the colors, they may continue to be applied even after you exit the process. To solve this, you have to print the "reset color" sequence (`Style.RESET_ALL`). `deinit` will not fix this.

**Comment by naltun** [comment]
@wiggin15 this is perfect. Thank you.
