### ISSUE TITLE
Migrate issues list from google code to github

### ISSUE THREAD

**Issue by tartley** [tartley/colorama#25]
Would this be helpful? Then the google code repo can be deleted.

Presumably we'd need to triage the issues as they were migrated - I suspect many of them have been fixed in recent commits.

**Comment by tartley** [comment]
Started migrating some things, prompted by some kind person submitting bug reports over on google code. Will hopefully finish later.

**Comment by msabramo** [comment]
This just became more important. See below email I just got:

![google code](https://cloud.githubusercontent.com/assets/305268/6631473/161de328-c8e4-11e4-9a62-cc0f2a1cd854.png)

Hello,

Earlier today, Google announced we will be turning down Google Code Project Hosting. The service started in 2006 with the goal of providing a scalable and reliable way of hosting open source projects. Since that time, millions of people have contributed to open source projects hosted on the site.

But a lot has changed since 2006. In the past nine years, many other options for hosting open source projects have popped up, along with vibrant communities of developers. It’s time to recognize that Google Code’s mission to provide open source projects a home has been accomplished by others, such as GitHub and Bitbucket.

We will be shutting down Google Code over the coming months. Starting today, the site will no longer accept new projects, but will remain functionally unchanged until August 2015. After that, project data will be read-only. Early next year, the site will shut down, but project data will be available for download in an archive format.

As the owner of the following projects, you have several options for migrating your data.

msabramo-pysqlite
msabramo-pymssql
msabramo-pymssql-osx-freetds
msabramo-pymssql-issue41
pymssql
msabramo-tox
msabramo-psutil-tox
msabramo-unittest-ext
The simplest option would be to use the Google Code Exporter, a new tool that will allow you to export your projects directly to GitHub. Alternatively, we have documentation on how to migrate to other services — GitHub, Bitbucket, and SourceForge — manually.

For more information, please see the Google Open Source blog or contact google-code-shutdown@google.com.

-The Google Code team

**Comment by tartley** [comment]
Acknowledged, I got the same email.

I'll spend an hour or two trying to migrate the last issues, but I'm keen not to just copy them all over blindly, to avoid generating needless work for everybody.

Does it make sense for anyone interested to get on a chat or skype call and we'll go through them together? This weekend? Who's interested? What timezones are people in? I'm London, UT+0.

**Comment by wiggin15** [comment]
@tartley , these are issues to migrate (still relevant):
28 (support context manager syntax)
33 (Windows sets the properties on both stdout and stderr regardless of the parameter passed)
57 (colorama.init breaks readline history)
58 (IPython colors are weird after init. I found the cause of this)
62 (pylint errors… not sure what we can do about that)

And I think the other issues should be closed:
63 (resolved and duplicates #48).
31 (won't fix, this makes the demos less readable)
34 (not a bug, I followed up on the issues on yanc and nose)
14 (cannot reproduce, and may be outdated)

**Comment by tartley** [comment]
Acknowledged, and many thanks for sorting through. I'll migrate them RIGHT NOW (!), and delete the google code project in a week or so.

**Comment by tartley** [comment]
All done.
