### ISSUE TITLE
Help Spyder implement ANSI color codes so Colorame works on it

### ISSUE THREAD

**Issue by maxborn** [tartley/colorama#270]
Hi guys,
I just noticed that Spyder, one of the most commonly used python IDEs that even comes default with Anaconda, doesn't support coloring its console output. I know this is an issue with Spyder, not Colorama, and I contacted their developers already. They told me they don't have time for the foreseeable future to work on implementing ANSI color support on their console, but that If I wanted to I could give it a try. They even pointed me to the right file (see note at the end).
I was just wondering if, given that many of the developers in this forum probably use Spyder and that you are already familiar with ANSI color codes, you would be willing to help.
I can assure you the scientific python community will be more than happy to see this implemented. For now, I'm sticking to Pycharm (which does support Colorama properly) given this problem.
Thanks in advance for taking the time to think about this.
And this is the reply I got from the Spyder team:
_I guess Colorama uses Ansi colors, so you need to see how to extend the code present in this file
https://github.com/jupyter/qtconsole/blob/master/qtconsole/ansi_code_processor.py
to make it our consoles work with it. That's because our IPython console is based on that.
_

**Comment by real-yfprojects** [comment]
Hello,
this issue can be closed , I think , since first of all spyder uses the *jupyter qtconsole* which this issue is related to. Therefore it is a issue on their side not on spyder's. Anyways the *qtconsole* supports ANSI codes since about 9 years *(it seems like)*. The problem is that *colorama* strips the ANSI codes because it thinks it isn't executed in a console. That is because `sys.stdout.isatty() == False` in the *qtconsole*. This seems to be *qtconsol*`'s fault.
