### ISSUE TITLE
Release patch version

### ISSUE THREAD

**Issue by DanielNoord** [tartley/colorama#341]
Hi maintainers,

Is there any chance that a patch version could be released? I know maintenance time is sparse for this project but `main` seems to have some useful fixes such as support for new python versions and my own fix in #339.
I would gladly help review any necessary PRs if those are blocking a release!

**Comment by tartley** [comment]
Hi people. Thanks for the thoughts. Arnon and I are emailing each other, and each have vacations coming up, but we have a window from around June 12th, we'll look at it then.

**Comment by tartley** [comment]
I'm going to try creating a release candidate now. Will append any significant commentary here. Dusting off my gaming rig to use as a Windows box for this, so anything could happen... :-)

**Comment by tartley** [comment]
Release 0.4.5rc1 is live on pypi.org. We will do some testing of our own over the next 24 hours, and aim to promote it to 0.4.5 (final release) tomorrow, with 24 hours to spare before I go on vacation. :-)

**Comment by tartley** [comment]
The release candidate looks fine to me. If we don't hear complaints from anyone else, I'll do a full release tomorrow morning.

**Comment by DanielNoord** [comment]
Thanks for all the work @tartley and have a good holiday!

**Comment by tartley** [comment]
'Tis done. Thanks to @wiggin15 for patiently sitting with me through yesterday's hour-long walkthrough of our "new" [release process](https://github.com/tartley/colorama/blob/master/README-hacking.md#release-checklist).  Went much faster today, since I didn't need to install Python, etc, on my gaming rig this time around.

0.4.5 final release is live, and works for me.
