### ISSUE TITLE
problem with just_fix_windows_console

### ISSUE THREAD

**Issue by nickums** [tartley/colorama#358]
on windows10 python38  colorama 0.4.,5

    from colorama import just_fix_windows_console

   ImportError: cannot import name 'just_fix_windows_console' from 'colorama'

**Comment by njsmith** [comment]
The problem is that you've been reading documentation from the future :-) `just_fix_windows_console` is a new feature in 0.4.6, and you have 0.4.5.

0.4.6 isn't released yet, but there is a prerelease on pypi for testing. If you want to try it out now, you should be able to `pip install --upgrade --pre colorama`. Or just wait a bit for the final release.

**Comment by nickums** [comment]
Thanks!  
the --pre colorama seems to use some lower-level dependencies than I have, so I still get background color only.
with best wishes, I look forward to future releases
