### ISSUE TITLE
Escape sequences are unprocessed on Windows with TERM set

### ISSUE THREAD

**Issue by msiemens** [tartley/colorama#48]
On Windows, when the environment variable `TERM` is set to any value, escape sequences will be printed unprocessed (no colored output). Concerning the values of `TERM`/the terminals where this happens, I'm still waiting for user feedback (see msiemens/PyGitUp#24).

According to `git bisect` this behaviour has been introduced in 961428e6c1c3a6855da5dedccfc418f295b54c25.

**Comment by krist10an** [comment]
I'm having the same issue using Colorama. I'm using bash from https://msysgit.github.io/, and that has TERM set to "cygwin" by default. Let me know if there is anything special I could test to help you verify (it wasn't clear to me in the linked issue)

**Comment by wiggin15** [comment]
Hmm... Bash should be able to process the escape sequences, because it's supposed to emulate a unix shell. Are you running bash from 'cmd' or from a Cygwin terminal?

It looks like a lot of people are encountering this problem so I think the commit (linked above) should be reverted. I just don't know what to do with Cygwin instead.

**Comment by krist10an** [comment]
I'm using bash that is included in the git package, and it is not started from cmd, but though the start menu. The shortcut command in the start menu is starting a separate command: ```"C:\Program Files (x86)\Git\bin\sh.exe" --login -i```

Also I don't have cygwin installed (and don't want that in the future either :smile:  )

**Comment by krist10an** [comment]
For reference, if I first run ```unset TERM``` then output ANSI with colorama the colors work as expected.

**Comment by ezk84** [comment]
The following script:

```python
#!/bin/env python
from colorama import init, Fore, Back, Style, deinit

init()
print("after init(): " +Fore.RED + 'some red text' +
      Fore.RESET + Back.RESET + Style.RESET_ALL)
print('back to normal now')

deinit()
init(convert=True)
print("after init(convert=True): " + Fore.RED + 'some red text' +
      Fore.RESET + Back.RESET + Style.RESET_ALL)
print('back to normal now')
```

Will output unprocessed escape sequences in the first instance and proper color in the last under Git for Windows. Interestingly, if I pipe the output to `cat`, the color is shown correctly in the first instance, and no colors nor escape characters are shown for the second. 
Under `cmd` the script works as expected.

**Comment by gvanem** [comment]
I had the same issue if e.g. `TERM=VT100` (that's needed in some Unix centric programs here).
I just added:
```
on_emulated_windows = False
```
in the **ansitowin32.py**, `AnsiToWin32()` constructor and I once again get colours.
BTW. I use JPsoft's 4NT. It works fine.

**Comment by shimizukawa** [comment]
Any progress?

**Comment by wiggin15** [comment]
First, we need to separate two different issues here:
* @msiemens is using PowerShell where 'convert' needs to be set to 'True' - and it's not because of the environment variable
* @ezk84 and @krist10an seem to be using a proper terminal emulator (msysgit's bash) where both conversion methods should work, but although convert gets set to 'False', the terminal doesn't recognize the escape sequences from colorama. Very strange.

In any case I'm not sure about this one. If I remove the environment variable check it will break code that actually runs on Cygwin (and probably other terminal emulators too, where the environment variable is set).

I'm leaving this ticket open until I find a better solution that works on all terminal types.

**Comment by tartley** [comment]
This is extremely speculative but: There's more than one way to spell any given ANSI sequence (e.g. there is an alternate 1-character . I've forever worried that Colorama only recognises a single

**Comment by tartley** [comment]
oops, closed accidentally. reopening.

**Comment by wiggin15** [comment]
I just pushed a commit that should resolve this issue.
Instead of looking at the environment variable, the code is now checking whether the conversion API works and turns on 'convert=True' only if it does. On the Cygwin terminal, the API doesn't work so convert will be False. The behavior on cmd and PowerShell should be back to normal.
It would be helpful if someone can check out the current branch and confirm that the fix works.

**Comment by shimizukawa** [comment]
Thanks!
I tried, it seems cmd and PowerShell are now fixed by using repository ver colorama (On Windows 10 build 10532 and Python 3.4).

**Comment by krist10an** [comment]
I tested with the tested with the script that @ezk84 made and it works nicely on my computer with Windows 7 in both Msysgit and cmd.

Thanks for the fix!

**Comment by wiggin15** [comment]
Thanks for your help! I'm closing this issue and I will release a new version soon.

**Comment by msiemens** [comment]
Thanks for your work, @wiggin15!

**Comment by tartley** [comment]
@wiggin15: I keep meaning to ask: Do you have any desire to transfer ownership of the canonical Colorama git repo to something other than me? Either yourself (since you're the most active developer), or maybe a new 'colorama' user or organisation, to help encourage contributions & a 'group ownership' mindset?  The downside is that it changes the repo url again.

Similarly, how about the PyPI project? I forget: Are you currently able to make new releases without needing my input?

Are there any other dangling tasks I can do to make your life easier?

Oh! I just realised - my contact details are prominently on the main README. Is there something more suitable we should replace them with? The colorama mailing list?

**Comment by tartley** [comment]
On reflection: Don't reply here: I'm creating an issue - lets discuss this there...

**Comment by tartley** [comment]
Finalise project ownership handover:
https://github.com/tartley/colorama/issues/71
