### ISSUE TITLE
IPython colors on Windows are weird after init()

### ISSUE THREAD

**Issue by tartley** [tartley/colorama#53]
What steps will reproduce the problem?
On a windows box: 
1. pip install ipython
2. ipython (to open ipython shell)
3. import colorama
4. colorama.init()

Dorks up the prompt and a lot of other ipython output

Reported by email from briford at the domain supercowpowers.com, Aug 11, 2014
Migrated from https://code.google.com/p/colorama/issues/detail?id=58

![screen shot 2014-08-11 at 2 56 30 pm](https://cloud.githubusercontent.com/assets/137979/7283237/37df3778-e92d-11e4-98ec-84a5b67caa9c.png)

- - -
From google code user szell.andris:

Hi,

I did not find a solution but found others having the same issue:

http://comments.gmane.org/gmane.comp.python.ipython.devel/13262

Last comment suggests "colorama ... and pyreadline (which IPython does use) both try to interpret ANSI escape codes and ... they conflict in some way" [lot of text replaced by dots].

Starting 'ipython console' instead of ipython solves the garbled prompt but breaks colorama features for me. (I am using windows.)

**Comment by wiggin15** [comment]
A comment in IPython (IPython/utils/coloransi.py):
"... the escapes are wrapped in \001 and \002 so that readline can properly know the length of each line and can wrap lines accordingly"
When the ANSI codes are stripped by colorama the \001 and \002 codes translate to the smilies we see.
A possible fix is changing the regex that colorama uses to capture these codes:

    -    ANSI_CSI_RE = re.compile('\033\[((?:\d|;)*)([a-zA-Z])')     # Control Sequence Introducer
    +    ANSI_CSI_RE = re.compile('\001?\033\[((?:\d|;)*)([a-zA-Z])\002?')     # Control Sequence Introducer
