### ISSUE TITLE
Why the white on Colorama is not really white but grey

### ISSUE THREAD

**Issue by Gryffoon** [tartley/colorama#93]
Why on windows the white on Colorama is not really white but grey.

![bug_to_report](https://cloud.githubusercontent.com/assets/15887222/14500467/90e88a5c-01a2-11e6-9413-4521777f7d6b.png)

As seen the word PASS and Warning which are colored in green and blue, their background is grey. 

Remark: We do not see this grey backoground on ubuntu/linux  with the same source code

**Comment by MinchinWeb** [comment]
On Windows, the "colours" are actually mapped to RGB values by CMD. So you have your "white" set to grey. This is typical though as "bright white" is typically set to be white while the "normal white" isn't as bright, so it comes across as grey.

See [here](http://www.howtogeek.com/howto/16815/how-to-personalize-the-windows-command-prompt/) under "Personalize Command Prompt Without Commands" on how you can change your CMD colours. See [here](https://github.com/neilpa/cmd-colors-solarized) for an example of someone's changed colours and the list of possible colours.

**Comment by wiggin15** [comment]
To paraphrase @MinchinWeb, `colorama.Fore.WHITE` is typically grey on both Windows and Linux, whereas `colorama.Style.BRIGHT + colorama.Fore.WHITE` (bright white) is typically real white on both. i.e. what you're seeing is intended. If you don't see this behavior on your linux machines, it may be because of your terminal's color settings - which may set "dim white" (grey) to actual white.
Unfortunately, `colorama.Style.BRIGHT` doesn't affect the background so you can't use it to achieve a "bright white" (real white) background.
You can try using `colorama.Back.LIGHTWHITE_EX` instead - e.g. `print colorama.Back.LIGHTWHITE_EX + "PASS" + colorama.Back.RESET`.

**Comment by Gryffoon** [comment]
OK thank you

**Comment by tartley** [comment]
If you're using colorama.Fore and colorama.Back attributes intensively, and/or finding them insufficient, then I'd recommend generating your ANSI codes using something like termcolor or maybe blessings instead, which might give you more flexibility and control. Use colorama only for converting ANSI into win32 calls for Windows compatibility, which is Colorama's core strength.

**Comment by MinchinWeb** [comment]
@tartley: I, for one, are glad that `colorama` has the basic ANSI code generators. Having them included made it much less involved to start adding colour to my Python projects. Thanks!

**Comment by nophead** [comment]
Ha, I have the same problem but on Ubuntu, not Windows. On Ubuntu my console is white but colorama white is grey. It matches my console on Windows though, where the console must actually be grey. Who knew!
